In [2]:
import numpy as np

In [3]:
my_list=[1,2,3]

In [4]:
np.array(my_list)  #casting my list into an array

array([1, 2, 3])

In [5]:
#2D array from a list of lists

In [6]:
my_mat= [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:

np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(25)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [12]:
np.zeros((2,3))    #A tuple signifying the rows and matrices

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10)    #10 EVENLY SPACED POINTS FROM 2 TO 23

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
 np.random.randint(5)

3

In [17]:
np.random.rand(5)

array([0.50438496, 0.38857097, 0.92930959, 0.42137763, 0.00786175])

In [18]:
np.random.rand(5,5)

array([[0.21659108, 0.79253608, 0.31376758, 0.26306765, 0.35070256],
       [0.13684597, 0.22025359, 0.72431861, 0.5123279 , 0.30868414],
       [0.86769801, 0.01935826, 0.07278403, 0.34298354, 0.8684125 ],
       [0.26972594, 0.54589829, 0.96117453, 0.07903812, 0.62302391],
       [0.26017594, 0.38828156, 0.02064187, 0.83684669, 0.81785575]])

In [19]:
arr= np.arange(25)

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.resize(5,5)

In [22]:
ranarr= np.random.randint(0,50,10)

In [23]:
ranarr.max()

49

In [24]:
ranarr.min()

5

In [25]:
#NumPy Indexing and Selection

In [26]:
import numpy as np
arr=np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [27]:
arr[8]

8

In [28]:
arr[1:5]

array([1, 2, 3, 4])

In [30]:
new_arr= np.arange(0,11)

In [31]:
slice_new_arr= new_arr[2:6]
slice_new_arr[:]=100     #slice_new_arr is not a copy but a refernce to the original array. we are broadcasting in this step
new_arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [35]:
#to make copy of an array
slice_new_arr_copy= new_arr.copy()
slice_new_arr_copy_mod=slice_new_arr_copy[2:6]
slice_new_arr_copy_mod[:]=99

In [36]:
new_arr

array([  0,   1, 100, 100, 100, 100,   6,   7,   8,   9,  10])

In [38]:
slice_new_arr_copy

array([ 0,  1, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [41]:
arr_2D= np.array([[5,10,15],[20 ,25, 30], [35, 40,45]])
arr_2D

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [42]:
arr_2D[1,2]

30

In [43]:
arr_2D[:2,1:]

array([[10, 15],
       [25, 30]])

In [45]:
arr_2D[1][2]   #DOUBLE BRACKET NOTATION

30

In [46]:
arrrrr= np.arange(1,11)

In [47]:
bool_arr= arrrrr %2==0
bool_arr

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [48]:
arrrrr[bool_arr]

array([ 2,  4,  6,  8, 10])

In [49]:
#NUMPY OPERATIONS